
export const DATABASE_FIELDS = [
  { key: 'pha_code', label: 'PHA Code', description: 'Unique identifier for the PHA' },
  { key: 'name', label: 'PHA Name', description: 'Official name of the housing authority', required: true },
  { key: 'address', label: 'Address', description: 'Street address' },
  { key: 'city', label: 'City', description: 'City name' },
  { key: 'state', label: 'State', description: 'State abbreviation (2 letters)' },
  { key: 'zip', label: 'ZIP Code', description: 'Postal code' },
  { key: 'phone', label: 'Phone', description: 'Contact phone number' },
  { key: 'email', label: 'Email', description: 'Contact email address' },
  { key: 'website', label: 'Website', description: 'Official website URL' },
  { key: 'supports_hcv', label: 'Supports HCV', description: 'Housing Choice Voucher support (Section 8)' },
  { key: 'waitlist_status', label: 'Waitlist Status', description: 'Current waitlist status' },
  { key: 'latitude', label: 'Latitude', description: 'Geographic latitude coordinate' },
  { key: 'longitude', label: 'Longitude', description: 'Geographic longitude coordinate' },
];

export const COMMON_MAPPINGS = {
  'PARTICIPANT_CODE': 'pha_code',
  'FORMAL_PARTICIPANT_NAME': 'name',
  'PARTICIPANT_NAME': 'name',
  'PHA_NAME': 'name',
  'STD_ADDR': 'address',
  'ADDRESS': 'address',
  'FULL_ADDRESS': 'address',
  'STD_CITY': 'city',
  'CITY': 'city',
  'STD_ST': 'state',
  'STATE': 'state',
  'STD_ZIP5': 'zip',
  'ZIP': 'zip',
  'HA_PHN_NUM': 'phone',
  'PHONE': 'phone',
  'HA_EMAIL_ADDR_TEXT': 'email',
  'EXEC_DIR_EMAIL': 'email',
  'EMAIL': 'email',
  'WEBSITE': 'website',
  'LAT': 'latitude',
  'LATITUDE': 'latitude',
  'LON': 'longitude',
  'LONGITUDE': 'longitude',
  'HA_PROGRAM_TYPE': 'supports_hcv',
  'WAITLIST_STATUS': 'waitlist_status',
};
