// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkvyzrxhfupjsrixfhhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdnl6cnhoZnVwanNyaXhmaGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDk1NDQsImV4cCI6MjA2Njk4NTU0NH0.V-vbZr2m1z_B_zoCDBTy5jDeZjOO0nENrKFCsH9DeBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});